apiVersion: v1
kind: Service
metadata:
  name: auth-mongo-nodeport-serv
spec:
  type: NodePort
  selector:
    app: auth-mongo
  ports:
    - name: auth-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
