apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          #image: us.gcr.io/ticketing-dev-403319/payments
          image: srnsatya/payments
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
            - name: MONGO_URI
              value: mongodb://payments-mongo-srv:27017/payments
            - name: NAT_URI
              value: 'http://nats-srv:4222'
            - name: NAT_CLUSTERID
              value: 'ticketing'
            - name: NAT_CLIENTID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 5000
      targetPort: 5000
